kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: configmaptest
parameters:
- name: NAME
  value: myconfigmap
- name: VALUE
  value: myvalue
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: '${NAME}-cfg'
  data:
    key: value
