#!/bin/bash

set -x

set -eo pipefail

# Copy files to target directories.

shopt -s dotglob

mv /tmp/src/* . || true

rm -rf /tmp/src

# Install any additional Python packages.

if [ -f requirements.txt ]; then
    pip install -r requirements.txt 
fi

# Fix up permissions.

fix-permissions /opt/app-root
