kind: TemplateBinding
apiVersion: example.openshift.dev/v1
metadata:
  name: database-beta
spec:
  template:
    database
  parameters:
  - name: APPLICATION_NAME
    valueFrom:
        fieldRef:
            fieldPath: metadata.name
