kind: Dropper
apiVersion: example.openshift.dev/v1
metadata:
  name: mongodb-gamma
spec:
  template:
    mongodb-ephemeral
  parameters:
  - name: DATABASE_SERVICE_NAME
    valueFrom:
        fieldRef:
            fieldPath: metadata.name
  - name: MEMORY_LIMIT
    valueFrom:
        configMapKeyRef:
            name: mongodb-settings
            key: MEMORY_LIMIT
  - name: MONGODB_PASSWORD
    valueFrom:
        secretKeyRef:
            name: mongodb-credentials
            key: MONGODB_PASSWORD
